### PR TITLE
pyvinecopulib 0.6.5 :snowflake:

### PR DESCRIPTION
**Pull request by lorepirri**
pyvinecopulib 0.6.5 :snowflake:

**Destination channel:** Snowflake

### Links

- [PKG-4852]
- dev_url (pypi): https://github.com/vinecopulib/pyvinecopulib/tree/v0.6.5
- conda-forge: _feedstock not found on conda-forge_
- pypi: https://pypi.org/project/pyvinecopulib/0.6.5
- pypi inspector: https://inspector.pypi.io/project/pyvinecopulib/0.6.5

### Explanation of changes:

- new feedstock
- recipe from grayskull
- patch build dependencies out of runtime dependencies
- upstream PR: https://github.com/vinecopulib/pyvinecopulib/pull/131

### Depends on

- AnacondaRecipes/wdm-feedstock#1
- AnacondaRecipes/vinecopulib-feedstock#1

[PKG-4852]: https://anaconda.atlassian.net/browse/PKG-4852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by tvatter** [comment]
Hi, maintainer of the pyvinecopulib package here :) I have pushed a PR to properly unvendor boost and eigen: it's on the [main branch already](https://github.com/vinecopulib/pyvinecopulib) and it will make its way to PyPI once the CI completes. Might I suggest to use this latest version ?

Note that the build now needs the path for the boost and eigen installs as environment variables, respectively  Boost_INCLUDE_DIR and EIGEN3_INCLUDE_DIR.

Typically, on Ubuntu, one can use:

```
sudo apt install libeigen3-dev libboost-all-dev
export Boost_INCLUDE_DIR=/usr/include
export EIGEN3_INCLUDE_DIR=/usr/include/eigen3
```

I don't know conda that well, but I expect that one should use the [boost feedstock](https://github.com/conda-forge/boost-feedstock) and [eigen feedstock](https://github.com/conda-forge/eigen-feedstock) ?

I'm going to try asap.

**Comment by tvatter** [comment]
@lorepirri I've submitted [a PR to conda forge for an updated recipe](https://github.com/conda-forge/staged-recipes/pull/26628).

**Comment by lorepirri** [comment]
> @lorepirri I've submitted [a PR to conda forge for an updated recipe](https://github.com/conda-forge/staged-recipes/pull/26628).

thank you @tvatter 

I did un-vendor `wdm` and will un-vendor `vinecopulib`. If that is required on `conda-forge` then you can use this as a reference.

**Comment by tvatter** [comment]
Hi, I have not unvendored wdm or vinecopulib because (a) we are authors for those libraries, and (b) they are far less useful without their python interface :)

**Comment by tvatter** [comment]
Another reason which makes it hard to unvendor vinecopulib: we extract the [doctstrings (`docstr.hpp`)](https://github.com/vinecopulib/pyvinecopulib/blob/main/src/docstr.hpp) from the C++ headers using pybind11's mkdoc. So it is important that the version of vinecopulib and that of pyvinecopulib are properly synced.

**Review by ViridianMelody — APPROVED** [review]

**Review by JamesRobertsonGames — APPROVED** [review]

**Review by ryanskeith — APPROVED** [review]
LGTM.  Though a couple things to consider:
They just updated to 0.6.6 last week.
We may want to cap the numpy version <2 to help migration (not required though).

**Comment by lorepirri** [comment]
> LGTM. Though a couple things to consider: They just updated to 0.6.6 last week. We may want to cap the numpy version <2 to help migration (not required though).

@ryanskeith I was too quick merging it, apologies.

The update to 0.6.6 is mostly to un-vendor `eigen` and `boost`, and a couple of changes in `src/main.cpp` and `src/docstr.hpp`. See https://github.com/vinecopulib/pyvinecopulib/compare/v0.6.5...v0.6.6

In the next version I'll add the upper bound to `numpy`, thanks!

**Pull request merged**
